# Generated by Django 5.0.6 on 2024-05-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_address', models.CharField(max_length=200)),
                ('buyer_email', models.CharField(max_length=100)),
                ('buyer_mobile', models.CharField(max_length=15)),
                ('buyer_gst', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_address', models.CharField(max_length=200)),
                ('seller_email', models.CharField(max_length=100)),
                ('seller_mobile', models.CharField(max_length=15)),
                ('seller_gst', models.CharField(max_length=20)),
            ],
        ),
    ]
