# Generated by Django 5.0.6 on 2024-05-28 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_buyer_seller'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
    ]
