# Generated by Django 5.0.6 on 2024-05-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='bill_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='item',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='bill',
            name='buyer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bill',
            name='seller',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='buyer_gst',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_gst',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
