# Generated by Django 5.0.6 on 2024-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_bill_bill_date_remove_bill_bill_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
