# Generated by Django 5.0.6 on 2024-05-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='b_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='b_pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='b_state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='s_city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='s_pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='s_state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
